# FreezeRun by cyantopinkz / gamelovemiku

msg: TEST FROM CONFIGGGGGGGGGG
arenas:
  test1_arena:
    id: test1_arena
    name: FREEZE01
    lobbytime: 60
    gametime: 180
    locations:
      lobby:
        world: world
        x: -8
        y: 70
        z: 7
      spawn:
        world: world
        x: -5
        y: 70
        z: 9


